# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-02 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gym', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_gym', models.ForeignKey(blank=True, help_text='Select the default gym for this installation. This will assign all new registered users to this gym and update all existing users without a gym.', null=True, on_delete=django.db.models.deletion.CASCADE, to='gym.Gym', verbose_name='Default gym')),
            ],
        ),
        migrations.CreateModel(
            name='LanguageConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(choices=[('1', 'Exercises'), ('2', 'Ingredients')], editable=False, max_length=2)),
                ('show', models.BooleanField(default=1)),
                ('language', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='language_source', to='core.Language')),
                ('language_target', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='language_target', to='core.Language')),
            ],
            options={
                'ordering': ['item', 'language_target'],
            },
        ),
    ]
