# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-08 10:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_auto_20170425_1230'),
        ('exercises', '0004_auto_20170508_1026'),
    ]

    operations = [
    ]
