# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-12 15:55
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_apiuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiuser',
            name='adding_permissions',
            field=models.BooleanField(default=False, verbose_name=django.contrib.auth.models.User),
        ),
    ]
