# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-18 08:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_userprofile_adding_permissions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='adding_permissions',
            new_name='creation_rights',
        ),
    ]
