# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-18 08:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20170518_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='creation_rights',
            new_name='adding_permissions',
        ),
    ]
